function _ai_save --argument-names cmd prompt --description 'Save a snippet as a fish script in ~/.local/bin'
    set -l dir ~/.local/bin
    mkdir -p $dir

    read -l -P "Script name: " name
    if test -z "$name"
        echo "Cancelled."
        return 1
    end

    # Keep it to something safe to put on PATH.
    set name (string replace -ra '[^A-Za-z0-9._-]' '-' -- $name)
    set -l path $dir/$name

    if test -e $path
        read -l -P "$path exists. Overwrite? [y/N] " ok
        contains -- $ok y Y; or return 1
    end

    begin
        echo '#!/usr/bin/env fish'
        echo "# Generated by aix on "(date -Iseconds)
        echo "# Prompt: $prompt"
        echo
        printf '%s\n' $cmd
    end >$path

    chmod +x $path

    set_color green
    echo "Saved $path"
    set_color normal

    if not contains -- $dir $PATH
        set_color yellow
        echo "~/.local/bin is not on PATH. Add it with:"
        echo "  fish_add_path ~/.local/bin"
        set_color normal
        return 0
    end

    read -l -P "Run $name now? [y/N] " ok
    if contains -- $ok y Y
        read -l -P "Arguments (if any): " args
        echo
        eval $path $args
    end
end
